#!/bin/bash

uname=`uname`
echo "System: $uname"

echo "Checking dependencies ..."
if test -f "conf.json"; then
    echo "conf.json exists"
else
    echo "Error: conf.json does not exist"
    exit
fi    
if ! command -v mysql &> /dev/null; then
    echo "Error: mysql found found. Please install mysql"
    exit
fi
if ! command -v jq &> /dev/null; then
    echo "Error: jq found found. Please install"
    exit
fi

DBUser=`cat conf.json | jq -r '.DBUser'`
DBHost=`cat conf.json | jq -r '.DBHost'`
DBName=`cat conf.json | jq -r '.DBName'`
echo "Testing mysql: mysql --user=$DBUser --host=$DBHost $DBName -p -e\"quit\""
# $(mysql --user=$DBUser --host=$DBHost $DBName -p -e"quit")
if mysql --user=$DBUser --host=$DBHost -p -e "USE $DBName"; then
    echo "Connect to database $DBName succeeded"
else
    echo "Error: Database \"$DBName\" not found or password is incorrect"
    exit
fi

echo "-----------------------------------------------"
echo "All dependencies checked. Invoking main process"
cmd=`cd $GOPATH/src/MathbloomBE; nohup go run $GOPATH/src/MathbloomBE/main.go >> $GOPATH/src/MathbloomBE/logs/mathbloom.log 2>&1 &`
echo "Sleeping 5 seconds to allow main process to start ..."
`sleep 5`
pid=$(lsof -nP -iTCP:8081 | grep LISTEN | awk '{print $2}')
echo "$pid" > $GOPATH/src/MathbloomBE/logs/run.pid
echo "Server started"
