#!/bin/bash

uname=`uname`
echo "System: $uname"

if [ ! -z "$GOPATH" ]; then
    echo "Checking existence of \$GOPATH: $GOPATH"
else
    echo "Error: \$GOPATH is not set"
    exit
fi

homedir="$GOPATH/src/MathbloomBE"

echo "Checking dependencies: $homedir/conf.json"
if test -f "$homedir/conf.json"; then
    echo "$homedir/conf.json exists"
else
    echo "Error: $homedir/conf.json does not exist"
    exit
fi
echo "Checking dependencies: mysql"
if ! command -v mysql &> /dev/null; then
    echo "Error: mysql not found. Please install mysql"
    exit
fi
echo "Checking dependencies: jq"
if ! command -v jq &> /dev/null; then
    echo "Error: jq found found. Please install jq"
    exit
fi
echo "Checking dependencies: nginx running?"
nginx=$(pgrep nginx)
if [[ "$nginx" == "" ]]; then
    echo "Error: nginx not running. Please start nginx"
    exit
fi

echo "Reading conf.json ..."
DBUser=`cat $homedir/conf.json | jq -r '.DBUser'`
DBHost=`cat $homedir/conf.json | jq -r '.DBHost'`
DBName=`cat $homedir/conf.json | jq -r '.DBName'`

echo "Testing mysql: mysql --user=$DBUser --host=$DBHost $DBName -p -e\"quit\""
if mysql --user=$DBUser --host=$DBHost -p -e "USE $DBName"; then
    echo "Connect to database $DBName succeeded"
else
    echo "Error: Database \"$DBName\" not found or password is incorrect"
    exit
fi

echo "-----------------------------------------------"
echo "All dependencies checked. Invoking main process"
cmd=`cd $homedir; nohup go run main.go >> logs/mathbloom.log 2>&1 &`
echo "Sleeping 5 seconds to allow main process to start ..."
`sleep 5`
pid=$(lsof -nP -iTCP:8081 | grep LISTEN | awk '{print $2}')
echo "$pid" > $homedir/logs/run.pid
echo "Server started (pid $pid)"
